language: python

python:
  - "3.7"

services:
  - docker
  - mongodb

env:
  global:
    - MONGO_ADDR=localhost:27017

install:
  - pip3 install -r app/src/requirements.txt
  - pip3 install pytest requests coverage

before_script:
  - mongo app --eval 'db.createUser({user:"$MONGO_USER",pwd:"$MONGO_PASS",roles:["readWrite"]});'

script:
  - coverage run -m pytest app/src

after_script:
  - coverage xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
