version: '2.4'

services:
  db:
    image: mongo:latest
    restart: on-failure
    volumes:
      - ./data/:/data/db

  app:
    build: app
    restart: on-failure
    depends_on:
      - db
    ports:
      - 80:8000
    volumes:
      - ./app/src/:/app
    pids_limit: 256
